version: '2'

services:
  db:
    image: mongo
    volumes:
      - $PWD/data/mongo:/data/db
  search:
    build: ./search
    image: search
    volumes:
      - $PWD/data/esdata:/usr/share/elasticsearch/data
  app:
    build: ./app
    image: app
    ports:
      - "80:80"
    links:
      - db:db
      - search:search
