version: '2'

services:
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  db:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
  search:
    build: ./search
    image: search
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
  app:
    build: ./app
    image: app
    ports:
      - "80:80"
    links:
      - db:db
      - search:search
      - redis:redis
